- id: terraform_docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: terraform_docs.sh
  args: ['asciidoc','./src > documentation/variables.adoc']
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$