- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: bin/terraform-fmt.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform-docs
  name: Terraform docs
  description: Generates table with inputs, outputs and variables based on the src folder
  entry: bin/terraform-docs.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform-validate
  name: Terraform validate
  description: Validates all Terraform configuration files
  entry: bin/terraform-validate.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: terraform-tflint
  name: tflint
  description: Linter for Terraform source code
  entry: bin/terraform-tflint.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: terraform-tfsec
  name: Terraform validate with tfsec
  description: Static analysis of Terraform templates to spot potential security issues.
  entry: bin/terraform-tfsec.sh
  language: script

- id: shellcheck
  name: Shellcheck Bash Linter
  description: Performs linting on bash scripts
  entry: bin/shellcheck.sh
  language: script

- id: yapf
  name: yapf
  description: yapf (Yet Another Python Formatter) is a python formatter from Google
  entry: bin/yapf.sh
  language: script
  files: \.py$
  exclude: >
    (?x)^(
      \.tox\/.*$|
      __pycache__\/.*$
    )$

- id: helmlint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: bin/helmlint.sh
  language: script
  files: \.((ya?ml)|(tpl))$